version: "3"
services:
  go-server:
    image: 'gocd/gocd-server:v22.3.0'
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:8153 || exit 1"]
      interval: 15s
      timeout: 5s
      retries: 3
    user: "1000:1000"
    ports:
      - "8153:8153" # for http
      - "8154:8154" # for https
    container_name: go-server
    volumes:
      - go-configs:/godata/config:z
      - /var/run/docker.sock:/var/run/docker.sock
      - go-plugins:/go-working-dir/plugins:z

volumes:
  go-plugins:
    driver_opts:
      o: bind
      type: none
      device: /home/${USER}/.gocd/plugins
  go-configs:
    driver_opts:
      o: bind
      type: none
      device: /home/${USER}/.gocd/configs
